baseURL = 'https://0xdrmnhttn13.github.io/dance-of-the-compilers/'
title = 'Dance of the Compilers'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'From algebra to silicon.'
  author = 'Augi'

[markup]
  [markup.highlight]
    style = 'github-dark'
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$', '$$']]
        inline = [['$', '$']]
