baseURL = 'https://0xdrmnhttn13.github.io/dance-of-the-compilers/'
title = 'Dance of the Compilers'
disableKinds = ['taxonomy', 'term']

enableRobotsTXT = true

[params]
  description = 'From algebra to silicon.'
  author = 'M Sidik Augi Rahmat'
  subtitle = 'To arrive where we started, and know the machine for the first time.'
  googleSiteVerification = 'UpGRUFcsNb-hjzsX6PQLmsr1Brd9DvUK4s8AItJO0WA'

[markup]
  [markup.highlight]
    style = 'github-dark'
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$', '$$']]
        inline = [['$', '$']]
